Description: " Creates resources (S3 Bucket, IAM roles, SageMaker Notebook instance) for ML Workshop via CloudFormation"
Parameters:

  NotebookInstanceType:
    Type: "String"
    Default: ml.t2.medium
    AllowedValues:
      - ml.t2.medium
      - ml.t2.large
      - ml.t2.xlarge
      - ml.t2.2xlarge
      - ml.m4.xlarge
      - ml.m4.2xlarge
      - ml.p2.xlarge
      - ml.p3.2xlarge
    Description: Enter a valid SageMaker notebook instance type. Defaults to ml.t2.medium.

Resources:
  SageMakerBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Sub sagemaker-${AWS::AccountId}-${AWS::Region}
      Tags:
        -
          Key: Name
          Value: SageMakerMLWorkshop

  SageMakerIamRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: Allow
            Principal:
              Service: sagemaker.amazonaws.com
            Action: sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryFullAccess"
        - "arn:aws:iam::aws:policy/AmazonSageMakerFullAccess"

  SageMakerNotebookInstance:
    Type: "AWS::SageMaker::NotebookInstance"
    Properties:
      NotebookInstanceName: MLWorkshopInstance
      InstanceType: !Ref NotebookInstanceType
      RoleArn: !GetAtt SageMakerIamRole.Arn

Outputs:
  SageMakerNotebookInstance:
    Value: !GetAtt SageMakerNotebookInstance.NotebookInstanceName
  S3Bucket:
    Value: !Ref SageMakerBucket
  IAMRole:
    Value: !GetAtt SageMakerIamRole.Arn
    Export:
      Name: SageMakerIamServiceRoleArn
